version: "2"

services:
  web:
     image: nginx:latest
     ports:
       - "8080:80"
     volumes:
       - ./public:/public
       - ./site.conf:/etc/nginx/conf.d/default.conf
  php:
      image: php:7-fpm
      volumes:
       - ./public:/public
       - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
